# Generated by Django 2.1.7 on 2019-02-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '付费'), (1, 'vip专享'), (2, '学位课程'), (3, '免费')]),
        ),
    ]
